version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  assignees:
  - julianolf
  allow:
  - dependency-type: direct
  - dependency-type: indirect
